In [50]:
import pandas as pd
import numpy as np

In [25]:
matches=pd.read_csv("matches.csv")
deliveries=pd.read_csv('deliveries.csv')

In [26]:
matches

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [27]:
matches.describe()

                 id  dl_applied  win_by_runs  win_by_wickets
count    756.000000  756.000000   756.000000      756.000000
mean    1792.178571    0.025132    13.283069        3.350529
std     3464.478148    0.156630    23.471144        3.387963
min        1.000000    0.000000     0.000000        0.000000
25%      189.750000    0.000000     0.000000        0.000000
50%      378.500000    0.000000     0.000000        4.000000
75%      567.250000    0.000000    19.000000        6.000000
max    11415.000000    1.000000   146.000000       10.000000

In [28]:
deliveries.describe()

,match_id,inning,over,ball,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs
count,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000
mean,1802.252957,1.482952,10.162488,3.615587,0.000452,0.036721,0.004936,0.021136,0.004183,0.000056,1.246864,0.067032,1.313897
std,3472.322805,0.502074,5.677684,1.806966,0.021263,0.251161,0.116480,0.194908,0.070492,0.016709,1.608270,0.342553,1.605422
min,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,190.000000,1.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,379.000000,1.000000,10.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
75%,567.000000,2.000000,15.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
max,11415.000000,5.000000,20.000000,9.000000,1.000000,5.000000,4.000000,5.000000,5.000000,5.000000,7.000000,7.000000,10.000000

In [29]:
TEAM_ALIAS = {
    "Delhi Daredevils":            "Delhi Capitals",
    "Kings XI Punjab":             "Punjab Kings",
    "Royal Challengers Bengaluru": "Royal Challengers Bangalore",
    "Deccan Chargers":             "Sunrisers Hyderabad",
}

for col in ["team1", "team2", "winner"]:
        matches[col] = matches[col].replace(TEAM_ALIAS)

In [30]:
matches['date']=pd.to_datetime(matches['date'],format='%d-%m-%Y')

In [31]:
matches['year']=matches['date'].dt.year

In [32]:
deliveries

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [33]:
matches

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,year
0,1,IPL-2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,2017
1,2,IPL-2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,2017
2,3,IPL-2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN,2017
3,4,IPL-2017,Indore,2017-04-08,Rising Pune Supergiant,Punjab Kings,Kings XI Punjab,field,normal,0,Punjab Kings,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,2017
4,5,IPL-2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Capitals,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,Mumbai,2019-05-05,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi,2019
752,11412,IPL-2019,Chennai,2019-05-07,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould,2019
753,11413,IPL-2019,Visakhapatnam,2019-05-08,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN,2019
754,11414,IPL-2019,Visakhapatnam,2019-05-10,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin,2019
755,11415,IPL-2019,Hyderabad,2019-05-12,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong,2019

In [34]:
total_score_df = deliveries.groupby(['match_id', 'inning'])['total_runs'].sum().reset_index()
total_score_df = total_score_df[total_score_df['inning'] == 1]
total_score_df['target_score'] = total_score_df['total_runs'] + 1
total_score_df = total_score_df[['match_id', 'target_score']]

In [35]:
match_df = matches.merge(total_score_df, left_on='id', right_on='match_id')
match_df = match_df[['match_id', 'team1', 'team2', 'winner', 'win_by_runs', 'win_by_wickets', 'target_score']]

In [36]:
delivery_df = deliveries[deliveries['inning'] == 2].copy()

In [37]:
delivery_df = delivery_df.merge(match_df, on='match_id')

In [39]:
delivery_df['current_score'] = delivery_df.groupby('match_id')['total_runs'].cumsum()
delivery_df['runs_left'] = delivery_df['target_score'] - delivery_df['current_score']

In [40]:
delivery_df['runs_left'] = delivery_df['runs_left'].clip(lower=0)

In [41]:
delivery_df['balls_bowled'] = (delivery_df['over'] - 1) * 6 + delivery_df['ball']
delivery_df['balls_left'] = 120 - delivery_df['balls_bowled']
delivery_df['balls_left'] = delivery_df['balls_left'].clip(lower=0) 
delivery_df['overs_left'] = delivery_df['balls_left'] / 6

In [42]:
delivery_df['player_dismissed'] = delivery_df['player_dismissed'].fillna("0")
delivery_df['player_dismissed'] = delivery_df['player_dismissed'].apply(lambda x: x if x == "0" else "1")
delivery_df['player_dismissed'] = delivery_df['player_dismissed'].astype(int)

In [43]:
delivery_df['wickets_fallen'] = delivery_df.groupby('match_id')['player_dismissed'].cumsum()
delivery_df['wickets_left'] = 10 - delivery_df['wickets_fallen']

In [44]:
delivery_df['result'] = (delivery_df['batting_team'] == delivery_df['winner']).astype(int)

In [51]:
delivery_df['crr'] = (delivery_df['current_score'] * 6) / delivery_df['balls_bowled']
delivery_df['rrr'] = np.where(delivery_df['balls_left'] > 0, 
                              (delivery_df['runs_left'] * 6) / delivery_df['balls_left'], 
                              0)

In [61]:
final_df = delivery_df[['match_id','batting_team', 'bowling_team', 
                        'over', 'ball', 'current_score', 'target_score', 'runs_left', 
                        'balls_left', 'overs_left', 'crr', 'rrr', 'wickets_fallen', 'wickets_left', 
                        'result']].copy()
delivery_df['balls_left'] = 120 - delivery_df['balls_bowled']
delivery_df['balls_left'] = delivery_df['balls_left'].clip(lower=0)

In [62]:
final_df

,match_id,batting_team,bowling_team,over,ball,current_score,target_score,runs_left,balls_left,overs_left,crr,rrr,wickets_fallen,wickets_left,result
0,1,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,1,208,207,119,19.833333,6.000000,10.436975,0,10,0
1,1,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,1,208,207,118,19.666667,3.000000,10.525424,0,10,0
2,1,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,1,208,207,117,19.500000,2.000000,10.615385,0,10,0
3,1,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,3,208,205,116,19.333333,4.500000,10.603448,0,10,0
4,1,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,7,208,201,115,19.166667,8.400000,10.486957,0,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86235,11415,Chennai Super Kings,Mumbai Indians,20,2,152,153,1,4,0.666667,7.862069,1.500000,5,5,0
86236,11415,Chennai Super Kings,Mumbai Indians,20,3,154,153,0,3,0.500000,7.897436,0.000000,5,5,0
86237,11415,Chennai Super Kings,Mumbai Indians,20,4,155,153,0,2,0.333333,7.881356,0.000000,6,4,0
86238,11415,Chennai Super Kings,Mumbai Indians,20,5,157,153,0,1,0.166667,7.915966,0.000000,6,4,0
86239,11415,Chennai Super Kings,Mumbai Indians,20,6,157,153,0,0,0.000000,7.850000,0.000000,7,3,0

In [63]:
features_to_keep = ['batting_team', 'bowling_team', 'target_score', 'runs_left', 
                    'balls_left', 'crr', 'rrr', 'wickets_left', 'result']

In [65]:
df_model = final_df[features_to_keep].copy()

In [66]:
df_encoded = pd.get_dummies(df_model, columns=['batting_team', 'bowling_team'], dtype=int)

In [68]:
df_encoded

,target_score,runs_left,balls_left,crr,rrr,wickets_left,result,batting_team_Chennai Super Kings,batting_team_Deccan Chargers,batting_team_Delhi Capitals,...,bowling_team_Kings XI Punjab,bowling_team_Kochi Tuskers Kerala,bowling_team_Kolkata Knight Riders,bowling_team_Mumbai Indians,bowling_team_Pune Warriors,bowling_team_Rajasthan Royals,bowling_team_Rising Pune Supergiant,bowling_team_Rising Pune Supergiants,bowling_team_Royal Challengers Bangalore,bowling_team_Sunrisers Hyderabad
0,208,207,119,6.000000,10.436975,10,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,208,207,118,3.000000,10.525424,10,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,208,207,117,2.000000,10.615385,10,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,208,205,116,4.500000,10.603448,10,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,208,201,115,8.400000,10.486957,10,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86235,153,1,4,7.862069,1.500000,5,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
86236,153,0,3,7.897436,0.000000,5,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
86237,153,0,2,7.881356,0.000000,4,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
86238,153,0,1,7.915966,0.000000,4,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
86239,153,0,0,7.850000,0.000000,3,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0

In [70]:
X = df_encoded.drop(columns=['result'])
y = df_encoded['result']

In [71]:
from sklearn.model_selection import train_test_split

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [73]:
def rename_team_cols(col_name):
    if col_name.startswith('batting_team_'):
        
        return col_name.replace('batting_team_', 'bat_')
    elif col_name.startswith('bowling_team_'):
       
        return col_name.replace('bowling_team_', 'bowl_')
    return col_name

X_train.columns = [rename_team_cols(col) for col in X_train.columns]
X_test.columns = [rename_team_cols(col) for col in X_test.columns]


print("Cleaned Column Names:")
print(list(X_train.columns))


X_train.to_csv('X_train.csv', index=False)
X_test.to_csv('X_test.csv', index=False)

Cleaned Column Names:
['target_score', 'runs_left', 'balls_left', 'crr', 'rrr', 'wickets_left', 'bat_Chennai Super Kings', 'bat_Deccan Chargers', 'bat_Delhi Capitals', 'bat_Delhi Daredevils', 'bat_Gujarat Lions', 'bat_Kings XI Punjab', 'bat_Kochi Tuskers Kerala', 'bat_Kolkata Knight Riders', 'bat_Mumbai Indians', 'bat_Pune Warriors', 'bat_Rajasthan Royals', 'bat_Rising Pune Supergiant', 'bat_Rising Pune Supergiants', 'bat_Royal Challengers Bangalore', 'bat_Sunrisers Hyderabad', 'bowl_Chennai Super Kings', 'bowl_Deccan Chargers', 'bowl_Delhi Capitals', 'bowl_Delhi Daredevils', 'bowl_Gujarat Lions', 'bowl_Kings XI Punjab', 'bowl_Kochi Tuskers Kerala', 'bowl_Kolkata Knight Riders', 'bowl_Mumbai Indians', 'bowl_Pune Warriors', 'bowl_Rajasthan Royals', 'bowl_Rising Pune Supergiant', 'bowl_Rising Pune Supergiants', 'bowl_Royal Challengers Bangalore', 'bowl_Sunrisers Hyderabad']

In [75]:
X_train=pd.read_csv("X_train.csv")

In [77]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68992 entries, 0 to 68991
Data columns (total 36 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   target_score                      68992 non-null  int64
 1   runs_left                         68992 non-null  int64
 2   balls_left                        68992 non-null  int64
 3   crr                               68992 non-null  float64
 4   rrr                               68992 non-null  float64
 5   wickets_left                      68992 non-null  int64
 6   bat_Chennai Super Kings           68992 non-null  int64
 7   bat_Deccan Chargers               68992 non-null  int64
 8   bat_Delhi Capitals                68992 non-null  int64
 9   bat_Delhi Daredevils              68992 non-null  int64
 10  bat_Gujarat Lions                 68992 non-null  int64
 11  bat_Kings XI Punjab               68992 non-null  int64
 12  bat_Kochi Tuskers Kerala          68992 non-null  int64
 13  bat_Kolkata Knight Riders         68992 non-null  int64
 14  bat_Mumbai Indians                68992 non-null  int64
 15  bat_Pune Warriors                 68992 non-null  int64
 16  bat_Rajasthan Royals              68992 non-null  int64
 17  bat_Rising Pune Supergiant        68992 non-null  int64
 18  bat_Rising Pune Supergiants       68992 non-null  int64
 19  bat_Royal Challengers Bangalore   68992 non-null  int64
 20  bat_Sunrisers Hyderabad           68992 non-null  int64
 21  bowl_Chennai Super Kings          68992 non-null  int64
 22  bowl_Deccan Chargers              68992 non-null  int64
 23  bowl_Delhi Capitals               68992 non-null  int64
 24  bowl_Delhi Daredevils             68992 non-null  int64
 25  bowl_Gujarat Lions                68992 non-null  int64
 26  bowl_Kings XI Punjab              68992 non-null  int64
 27  bowl_Kochi Tuskers Kerala         68992 non-null  int64
 28  bowl_Kolkata Knight Riders        68992 non-null  int64
 29  bowl_Mumbai Indians               68992 non-null  int64
 30  bowl_Pune Warriors                68992 non-null  int64
 31  bowl_Rajasthan Royals             68992 non-null  int64
 32  bowl_Rising Pune Supergiant       68992 non-null  int64
 33  bowl_Rising Pune Supergiants      68992 non-null  int64
 34  bowl_Royal Challengers Bangalore  68992 non-null  int64
 35  bowl_Sunrisers Hyderabad          68992 non-null  int64
dtypes: float64(2), int64(34)
memory usage: 18.9 MB

In [78]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV
import time

In [79]:
xgb_model = xgb.XGBClassifier(eval_metric='logloss', random_state=42)

In [84]:
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [3, 5],                
    'learning_rate': [0.05, 0.1],
    'reg_alpha': [0, 0.5, 1],           
    'reg_lambda': [1, 5, 10],            
    'gamma': [0, 0.1, 0.5]               
}

In [85]:
grid_search = GridSearchCV(
    estimator=xgb_model, 
    param_grid=param_grid, 
    cv=3,                 
    scoring='accuracy',   
    n_jobs=-1,            
    verbose=2             
)

In [86]:
print("Starting Hyperparameter Tuning. This may take a few minutes...")
start_time = time.time()

grid_search.fit(X_train, y_train)

end_time = time.time()
print(f"\nTuning completed in {end_time - start_time:.2f} seconds.")
print(f"Best Parameters Found: {grid_search.best_params_}")
print(f"Best Cross-Validation Accuracy: {grid_search.best_score_:.4f}")

Starting Hyperparameter Tuning. This may take a few minutes...
Fitting 3 folds for each of 216 candidates, totalling 648 fits

Tuning completed in 815.87 seconds.
Best Parameters Found: {'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200, 'reg_alpha': 1, 'reg_lambda': 1}
Best Cross-Validation Accuracy: 0.9527

In [87]:
best_xgb_model = grid_search.best_estimator_
best_xgb_model.save_model('xgb_win_prob_model.json')

In [88]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [90]:
y_pred = best_xgb_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"\n=== Model Evaluation ===")
print(f"Overall Accuracy: {accuracy * 100:.2f}%\n")

=== Model Evaluation ===
Overall Accuracy: 95.52%

In [91]:
print(classification_report(y_test, y_pred, target_names=['Loss (0)', 'Win (1)']))

              precision    recall  f1-score   support

    Loss (0)       0.98      0.95      0.96     10160
     Win (1)       0.93      0.97      0.95      7088

    accuracy                           0.96     17248
   macro avg       0.95      0.96      0.95     17248
weighted avg       0.96      0.96      0.96     17248

In [92]:
print("=== Confusion Matrix ===")
conf_matrix = confusion_matrix(y_test, y_pred)
print(pd.DataFrame(conf_matrix, 
                   index=['Actual Loss', 'Actual Win'], 
                   columns=['Predicted Loss', 'Predicted Win']))

=== Confusion Matrix ===
             Predicted Loss  Predicted Win
Actual Loss            9630            530
Actual Win              243           6845